# Generated by Django 5.0.1 on 2024-01-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoId', models.CharField(max_length=11, unique=True)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('publishedAt', models.DateTimeField()),
                ('thumbnailUrls', models.JSONField()),
            ],
            options={
                'indexes': [models.Index(fields=['publishedAt'], name='getvideo_vi_publish_e5fe25_idx'), models.Index(fields=['title'], name='getvideo_vi_title_1b7968_idx'), models.Index(fields=['description'], name='getvideo_vi_descrip_c78167_idx'), models.Index(fields=['videoId'], name='getvideo_vi_videoId_16316a_idx')],
            },
        ),
    ]
