# Generated by Django 5.0.1 on 2024-01-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getvideo', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['videoId'], name='getvideo_vi_videoId_16316a_idx'),
        ),
    ]
